version: "3.9"
services:
  authservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authservice
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: authservice_db
      DB_USER:
      DB_PASSWORD:
      JWT_SECRET:
      JWT_EXPIRATION: "3600000"
      X_API_KEY:
    depends_on:
      - db
      - kafka
    volumes:
      - ./db/migration:/app/db/migration
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: authservice_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/migration:/app/db/migration
    restart: unless-stopped

volumes:
  pgdata:
    driver: local